language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install coveralls"
# command to run tests
script:
  coverage run --source=visualcaptcha test.py
after_success:
  coveralls